### ISSUE TITLE
Reqwest error 400 for opencritic api

### ISSUE THREAD

**Issue by PicantePeperoni** [drrlvn/entertainme#18]
Hello,
I am reciving a 400 error for opencritic api when I try to use entertainme witht he following command:

> entertainme halo
Error: Reqwest(reqwest::Error { kind: Status(400), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.opencritic.com")), port: None, path: "/api/game/search", query: Some("criteria=halo"), fragment: None } })

Im not sure if i have not formatted the request appropriately but would appreciate the help.
Thank you!

**Comment by drrlvn** [comment]
OpenCritic was broken and is now fixed, thanks for reporting!
